### ISSUE TITLE
 locale_file_path.empty problem

### ISSUE THREAD

**Issue by omarpta** [CzarekTomczak/cefcapi#2]
Hi man... in your example, after callback "on_register_custom_schemes", i'm having this error, what i missing?
 
on_register_custom_schemes
[0801/004832:WARNING:resource_bundle.cc(280)] locale_file_path.empty()
[0801/004832:FATAL:main_delegate.cc(499)] Check failed: !loaded_locale.empty(). Locale could not be found for en-US

Ihave the exactly same version of cefcapi requirements: 
cef_binary_3.1750.1629_linux64_client

Please help me...

**Comment by CzarekTomczak** [comment]
You are missing some of the binaries in the Release/ directory. Check that you've copied all binary files (.pak files, locales/ subdir).

**Comment by omarpta** [comment]
Thanks, i got it.
